
#!/usr/bin/env python3
"""
CMSSL17_offline.py

Run CMSSL17's model *using prebuilt tokens* produced by offline_ingest.py.
This mirrors the training/eval flow in CMSSL17.py but reads dataset splits
from OUT_ROOT/meta.json and week meta files, avoiding any online feature building.

Env vars:
  BYBIT_OUT_ROOT=/path/to/offline_ingest_output_root      (REQUIRED)
  BYBIT_USE_IN_MEMORY=0|1   # 1 = load all chunks into RAM (faster but memory heavy). Default 1
  BYBIT_WORKERS=8           # train DataLoader workers. Default 8; val/test use max(1, min(4, BYBIT_WORKERS//2)).

Split metadata requirement:
  - This script requires meta.json['splits'] generated by offline_ingest.
  - If split metadata is missing or incomplete, it raises with an actionable error.
  - Uses explicit train/val/test week keys and train_ts_range/val_ts_range/test_ts_range.
  - Applies half-open masks start <= ts < end using per-chunk ts_*.npy.

Files layout expected (created by offline_ingest.py):
  OUT_ROOT/
    meta.json                           # global manifest
    <WEEK_KEY>/
      meta_week.json
      Xcore_000.npy, Xaux_000.npy, y_000.npy
      Xcore_001.npy, Xaux_001.npy, y_001.npy
      ...

This script attempts to *import* model and utils from CMSSL17.py to avoid duplication.

Time-grid contract is centralized in CMSSL17.py.
"""

import os, sys, math
from typing import List, Dict, Tuple, Iterable
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

from offline_tokens import (
    read_json,
    load_global_meta,
    ChunkRef,
)

# ---------------- Import from CMSSL17 ----------------
# Configure CUDA allocator only for this entrypoint execution to avoid
# import-time side effects when CMSSL17 is used as a library module.
if __name__ == "__main__":
    os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from CMSSL17 import (  # type: ignore
    # model + args
    SAMBA, ModelArgs,
    # core hypers
    LOOKBACK, AUX_DIM, HORIZONS_MS, NUM_HORIZONS, HORIZON_WEIGHTS,
    BATCH_SIZE, EPOCHS, LR, PATIENCE,
    # schedules / deltas / lambdas
    DIR_MASK_TAIL_FRACTION,
    DELTA_RET, DELTA_LOGVOL,
    LAMBDA_BCE, LAMBDA_RET, LAMBDA_VOL,
    DMODEL, MAMBA_LAYERS,
    PRIMARY_METRIC_HORIZON_MS,
    # utils
    huber_loss, ema_update, binary_auc_from_logits,
    SINGLE_WEEK_PATIENCE, get_primary_metric_mode, compute_primary_metric, is_metric_improved,
    # optimizer
    SAM,
    TIME_GRID_STEP_MS,
    TIME_GRID_GUARD_MS,
)

# ---------------- Config via env ----------------
OUT_ROOT = os.environ.get("BYBIT_OUT_ROOT", "").strip()
USE_IN_MEMORY = int(os.environ.get("BYBIT_USE_IN_MEMORY", "1")) == 1
WORKERS_TRAIN = int(os.environ.get("BYBIT_WORKERS", "8"))
WORKERS_VAL   = max(1, min(4, WORKERS_TRAIN // 2))
AMP_ENABLED   = int(os.environ.get("BYBIT_AMP", "0")) == 1
LOG_EVERY     = int(os.environ.get("BYBIT_LOG_EVERY", "50"))
EXPECTED_GRID_STEP_MS = int(TIME_GRID_STEP_MS)
EXPECTED_GRID_GUARD_MS = int(TIME_GRID_GUARD_MS)
EXPECTED_DECISION_POLICY = "ob_only_grid_quantized"

assert OUT_ROOT, "Set BYBIT_OUT_ROOT to the root created by offline_ingest.py"

def _range_from_splits(splits: dict, key: str) -> tuple[int, int]:
    if key not in splits:
        raise KeyError(f"meta['splits'] missing required key '{key}'.")

    bounds = splits[key]
    if not isinstance(bounds, dict):
        raise ValueError(f"meta['splits']['{key}'] must be a dict.")
    if "min" not in bounds or "max" not in bounds:
        raise KeyError(f"meta['splits']['{key}'] must include both 'min' and 'max'.")

    try:
        lo = int(bounds["min"])
        hi = int(bounds["max"])
    except (TypeError, ValueError):
        raise ValueError(f"meta['splits']['{key}'] min/max must be integers.")

    if lo >= hi:
        raise ValueError(f"meta['splits']['{key}'] must satisfy min < max.")

    return lo, hi


def require_complete_splits(meta: dict) -> dict:
    if "splits" not in meta:
        raise KeyError(
            "meta.json missing required key 'splits'. Run offline_ingest to generate offline dataset metadata."
        )
    splits = meta["splits"]
    if not isinstance(splits, dict):
        raise KeyError("meta['splits'] must be a dict. Rerun offline_ingest.")

    if "weeks_in_order" not in meta:
        raise KeyError("meta.json missing required key 'weeks_in_order'. Rerun offline_ingest.")
    weeks_in_order = meta["weeks_in_order"]
    if not isinstance(weeks_in_order, list) or not weeks_in_order:
        raise KeyError("meta.json missing required non-empty key 'weeks_in_order'. Rerun offline_ingest.")

    time_grid = meta.get("time_grid")
    if not isinstance(time_grid, dict):
        raise KeyError(
            "meta.json missing required key 'time_grid'. "
            f"Rerun offline_ingest so timestamps are exported on the canonical {EXPECTED_GRID_STEP_MS}ms grid."
        )
    step_ms = time_grid.get("step_ms")
    guard_ms = time_grid.get("guard_ms")
    try:
        step_ms_int = int(step_ms)
        guard_ms_int = int(guard_ms)
    except (TypeError, ValueError):
        raise ValueError(
            "meta.json has invalid time_grid types. "
            f"Expected integer step_ms/guard_ms, got step_ms={step_ms!r}, guard_ms={guard_ms!r}. "
            "Rerun offline_ingest to regenerate grid-quantized splits."
        )
    if step_ms_int != EXPECTED_GRID_STEP_MS or guard_ms_int != EXPECTED_GRID_GUARD_MS:
        raise ValueError(
            "meta.json has incompatible time_grid settings. "
            f"Expected step_ms={EXPECTED_GRID_STEP_MS}, guard_ms={EXPECTED_GRID_GUARD_MS}; "
            f"got step_ms={step_ms_int!r}, guard_ms={guard_ms_int!r}. "
            "Rerun offline_ingest to regenerate grid-quantized splits."
        )

    decision_policy = meta.get("decision_policy")
    if decision_policy != EXPECTED_DECISION_POLICY:
        raise ValueError(
            "meta.json has incompatible decision_policy. "
            f"Expected '{EXPECTED_DECISION_POLICY}' (canonical grid-quantized policy); "
            f"got {decision_policy!r}. "
            "Rerun offline_ingest to regenerate metadata with grid quantization enabled."
        )

    required_keys = {
        "train", "val", "test", "holdout_week",
        "train_ts_range", "val_ts_range", "test_ts_range",
    }
    if not required_keys.issubset(splits):
        raise KeyError("meta['splits'] missing train/val/test/holdout_week or *_ts_range. Rerun offline_ingest.")

    for key in ("train", "val", "test"):
        vals = splits[key]
        if not isinstance(vals, list) or not vals or not all(isinstance(w, str) and w for w in vals):
            raise KeyError(f"meta['splits']['{key}'] must be a non-empty list[str]. Rerun offline_ingest.")

    holdout_week = splits["holdout_week"]
    if not isinstance(holdout_week, str) or not holdout_week:
        raise KeyError("meta['splits']['holdout_week'] must be a non-empty string. Rerun offline_ingest.")

    def _parse_half_open_range(name: str) -> tuple[int, int]:
        try:
            return _range_from_splits(splits, name)
        except (KeyError, ValueError) as exc:
            raise type(exc)(f"{exc} Rerun offline_ingest.")

    tr_lo, tr_hi = _parse_half_open_range("train_ts_range")
    va_lo, va_hi = _parse_half_open_range("val_ts_range")
    te_lo, te_hi = _parse_half_open_range("test_ts_range")

    if max(va_lo, te_lo) < min(va_hi, te_hi):
        raise ValueError("meta['splits'] val_ts_range and test_ts_range must not overlap.")

    if holdout_week not in splits["val"] or holdout_week not in splits["test"]:
        raise ValueError("meta['splits']['holdout_week'] must be included in both val and test week lists.")

    known_weeks = set(weeks_in_order)
    all_refs = set(splits["train"]) | set(splits["val"]) | set(splits["test"]) | {holdout_week}
    missing_weeks = sorted(w for w in all_refs if w not in known_weeks)
    if missing_weeks:
        raise KeyError(f"meta['splits'] references week(s) not present in meta['weeks_in_order']: {missing_weeks}")

    if holdout_week != weeks_in_order[-1]:
        raise ValueError("meta['splits']['holdout_week'] must equal weeks_in_order[-1].")

    return {
        "splits": splits,
        "weeks_in_order": weeks_in_order,
        "split_ranges": {
            "train": (tr_lo, tr_hi),
            "val": (va_lo, va_hi),
            "test": (te_lo, te_hi),
        },
    }


def build_chunk_refs_by_ts(meta_week_path: Path, start: int, end: int) -> List[ChunkRef]:
    """
    Build ChunkRefs for rows whose timestamps satisfy start <= ts < end.

    The function performs contiguous slicing per chunk via searchsorted on each
    chunk's ts file and avoids materializing full boolean masks / index lists.
    """
    if end < start:
        raise ValueError(f"Invalid ts range: start={start} must be <= end={end}")

    wmeta = read_json(meta_week_path)
    week_dir = meta_week_path.parent
    refs: List[ChunkRef] = []

    for idx, ch in enumerate(wmeta.get("chunks", [])):
        files = ch.get("files", {})
        ts_rel = files.get("ts")
        if not ts_rel:
            raise KeyError(
                f"Chunk {idx} in {meta_week_path} is missing files['ts']; cannot slice by timestamp"
            )

        ts_arr = np.load(week_dir / ts_rel, mmap_mode="r")
        if ts_arr.ndim != 1:
            raise ValueError(
                f"Expected 1D ts array in chunk {idx} ({week_dir / ts_rel}), got shape={ts_arr.shape}"
            )

        # Safety check: searchsorted semantics require non-decreasing input.
        if ts_arr.size > 1 and not np.all(ts_arr[1:] >= ts_arr[:-1]):
            raise ValueError(
                f"Timestamp file is not non-decreasing for chunk {idx}: {week_dir / ts_rel}"
            )

        if ts_arr.size and not np.all(ts_arr % EXPECTED_GRID_STEP_MS == 0):
            bad_i = int(np.flatnonzero(ts_arr % EXPECTED_GRID_STEP_MS != 0)[0])
            bad_ts = int(ts_arr[bad_i])
            raise ValueError(
                "Off-grid timestamp detected while building chunk refs. "
                f"week_meta={meta_week_path}, chunk={idx}, ts_file={week_dir / ts_rel}, "
                f"bad_index={bad_i}, bad_ts={bad_ts}. "
                "Rerun offline_ingest to regenerate grid-aligned timestamps."
            )

        l = int(np.searchsorted(ts_arr, start, side="left"))
        r = int(np.searchsorted(ts_arr, end, side="left"))

        if r > l:
            refs.append(ChunkRef(
                week_dir=week_dir,
                core_file=week_dir / files["core"],
                aux_file=week_dir / files["aux"],
                y_file=week_dir / files["y"],
                n=r - l,
                offset=l,
            ))

    return refs

# ---------------- Dataset (streaming from .npy chunks) ----------------
class NpyChunksDataset(Dataset):
    def __init__(self, chunk_refs: List[ChunkRef], feature_dim_total: int):
        """
        chunk_refs: list of chunks in chronological order (kept as given)
        feature_dim_total: F (including AUX_DIM)
        """
        self.refs = list(chunk_refs)
        self.F = int(feature_dim_total)
        self.F_core = self.F - AUX_DIM
        if self.F_core <= 0:
            raise ValueError(f"feature_dim_total ({self.F}) must exceed AUX_DIM ({AUX_DIM})")

        # prefix sums for O(log N) lookup
        self.starts = []
        total = 0
        for r in self.refs:
            self.starts.append(total)
            total += r.n
        self.total = total

        # small cache of currently loaded memory-mapped arrays per process
        self._cache: Dict[Tuple[str, int], Tuple[np.memmap, np.memmap, np.memmap]] = {}
        self._lru: List[Tuple[str, int]] = []
        self._cap = 8  # keep up to 8 chunks mapped

    def __len__(self):
        return self.total

    def _locate(self, idx: int) -> Tuple[int, int]:
        # binary search on starts
        lo, hi = 0, len(self.starts) - 1
        while lo <= hi:
            mid = (lo + hi) // 2
            start = self.starts[mid]
            next_start = self.starts[mid + 1] if mid + 1 < len(self.starts) else self.total
            if start <= idx < next_start:
                return mid, idx - start
            elif idx < start:
                hi = mid - 1
            else:
                lo = mid + 1
        raise IndexError(idx)

    def _load_chunk(self, i: int) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        ref = self.refs[i]
        key = (str(ref.week_dir), i)
        if key in self._cache:
            # move to end of LRU
            try:
                self._lru.remove(key)
            except ValueError:
                pass
            self._lru.append(key)
            return self._cache[key]
        # mmap lazy
        Xc = np.load(ref.core_file, mmap_mode='r')
        Xa = np.load(ref.aux_file,  mmap_mode='r')
        Y  = np.load(ref.y_file,    mmap_mode='r')
        self._cache[key] = (Xc, Xa, Y)
        self._lru.append(key)
        if len(self._lru) > self._cap:
            evict_key = self._lru.pop(0)
            try:
                del self._cache[evict_key]
            except KeyError:
                pass
        return Xc, Xa, Y

    def __getitem__(self, idx: int):
        ci, offset_in_dataset = self._locate(idx)
        ref = self.refs[ci]
        Xc, Xa, Y = self._load_chunk(ci)

        idx_in_file = ref.offset + offset_in_dataset

        core = np.asarray(Xc[idx_in_file], dtype=np.float32)
        aux  = np.asarray(Xa[idx_in_file], dtype=np.float32)
        x = np.concatenate([core, aux], axis=-1)
        if not x.flags.writeable:
            x = x.copy()
        y = np.asarray(Y[idx_in_file], dtype=np.float32)
        if not y.flags.writeable:
            y = y.copy()
        return torch.from_numpy(x), torch.from_numpy(y)


def load_split_in_memory_ts(split_week_paths: List[Path], start: int, end: int) -> Tuple[np.ndarray, np.ndarray, int]:
    """Load rows in start <= ts < end across weeks into RAM. Returns X [N, L, F], y [N, 2H], F."""
    if end < start:
        raise ValueError(f"Invalid ts range: start={start} must be <= end={end}")

    Xs, Ys = [], []
    feat_dim = None
    for wp in split_week_paths:
        wmeta = read_json(wp)
        F_total = int(wmeta["feature_dim_total"])
        if feat_dim is None:
            feat_dim = F_total
        elif feat_dim != F_total:
            raise ValueError(f"Feature dim mismatch between weeks: {feat_dim} vs {F_total}")

        week_dir = wp.parent
        for idx, ch in enumerate(wmeta.get("chunks", [])):
            files = ch.get("files", {})
            ts_rel = files.get("ts")
            if not ts_rel:
                raise KeyError(
                    f"Chunk {idx} in {wp} is missing files['ts']; cannot slice by timestamp"
                )

            ts_arr = np.load(week_dir / ts_rel, mmap_mode="r")
            if ts_arr.ndim != 1:
                raise ValueError(
                    f"Expected 1D ts array in chunk {idx} ({week_dir / ts_rel}), got shape={ts_arr.shape}"
                )

            # Safety check: searchsorted semantics require non-decreasing input.
            if ts_arr.size > 1 and not np.all(ts_arr[1:] >= ts_arr[:-1]):
                raise ValueError(
                    f"Timestamp file is not non-decreasing for chunk {idx} in {wp}: "
                    f"{week_dir / ts_rel}; ts must be non-decreasing for range slicing"
                )

            l = int(np.searchsorted(ts_arr, start, side="left"))
            r = int(np.searchsorted(ts_arr, end, side="left"))
            if r <= l:
                continue

            if not np.all(ts_arr[l:r] % EXPECTED_GRID_STEP_MS == 0):
                rel_i = int(np.flatnonzero(ts_arr[l:r] % EXPECTED_GRID_STEP_MS != 0)[0])
                bad_i = l + rel_i
                bad_ts = int(ts_arr[bad_i])
                raise ValueError(
                    "Off-grid timestamp detected in selected split range. "
                    f"week_meta={wp}, chunk={idx}, ts_file={week_dir / ts_rel}, "
                    f"slice=({l}:{r}), bad_index={bad_i}, bad_ts={bad_ts}. "
                    "Rerun offline_ingest to regenerate grid-aligned timestamps."
                )

            Xc = np.load(week_dir / files["core"])
            Xa = np.load(week_dir / files["aux"])
            Y = np.load(week_dir / files["y"])
            Xs.append(np.concatenate([Xc[l:r], Xa[l:r]], axis=-1))
            Ys.append(Y[l:r])

    if not Xs:
        return (
            np.empty((0, LOOKBACK, feat_dim or 0), np.float32),
            np.empty((0, 2 * NUM_HORIZONS), np.float32),
            (feat_dim or 0),
        )
    X = np.concatenate(Xs, axis=0).astype(np.float32, copy=False)
    y = np.concatenate(Ys, axis=0).astype(np.float32, copy=False)
    return X, y, int(feat_dim)

# ---------------- Directional-noise filter quantiles from TRAIN set ----------------
def compute_dir_mask_quantiles_from_ytrain(y_train: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    # Label-space noise trimming: keep only mid-quantile return magnitudes per direction/horizon;
    # this is unrelated to model token dropout objectives.
    y_ret = y_train[:, :NUM_HORIZONS].astype(np.float32)
    def _compute_trim_bounds(arr: np.ndarray) -> Tuple[float, float]:
        if arr.size == 0:
            return float("inf"), float("-inf")
        try:
            lo = float(np.quantile(arr, DIR_MASK_TAIL_FRACTION, method="linear"))
            hi = float(np.quantile(arr, 1.0 - DIR_MASK_TAIL_FRACTION, method="linear"))
        except TypeError:
            lo = float(np.quantile(arr, DIR_MASK_TAIL_FRACTION, interpolation="linear"))
            hi = float(np.quantile(arr, 1.0 - DIR_MASK_TAIL_FRACTION, interpolation="linear"))
        return lo, hi

    pos_lo_list = []
    pos_hi_list = []
    neg_lo_list = []
    neg_hi_list = []
    print("[directional-noise-filter quantiles]")
    for idx, horizon in enumerate(HORIZONS_MS):
        horizon_returns = y_ret[:, idx]
        pos_returns = horizon_returns[horizon_returns > 0]
        neg_returns = horizon_returns[horizon_returns < 0]
        pos_lo, pos_hi = _compute_trim_bounds(pos_returns)
        neg_lo, neg_hi = _compute_trim_bounds((-neg_returns))
        pos_lo_list.append(pos_lo); pos_hi_list.append(pos_hi)
        neg_lo_list.append(neg_lo); neg_hi_list.append(neg_hi)
        print(f"  {horizon}ms → pos:[{pos_lo:.3e}, {pos_hi:.3e}]  neg|mag:[{neg_lo:.3e}, {neg_hi:.3e}] (tail {DIR_MASK_TAIL_FRACTION:.2%})")

    pos_lo_arr = np.array(pos_lo_list, dtype=np.float32)
    pos_hi_arr = np.array(pos_hi_list, dtype=np.float32)
    neg_lo_arr = np.array(neg_lo_list, dtype=np.float32)
    neg_hi_arr = np.array(neg_hi_list, dtype=np.float32)

    pos_mask = y_ret > 0
    neg_mask = y_ret < 0
    neg_mag = -y_ret
    keep_mask = (
        (pos_mask & (y_ret >= pos_lo_arr) & (y_ret <= pos_hi_arr))
        | (neg_mask & (neg_mag >= neg_lo_arr) & (neg_mag <= neg_hi_arr))
    )
    kept_per_h = keep_mask.mean(axis=0)
    per_horizon_line = " | ".join(
        f"{horizon}ms={float(kept):.2%}" for horizon, kept in zip(HORIZONS_MS, kept_per_h)
    )
    print(f"[dir-mask] kept per horizon: {per_horizon_line}")

    main_idx = NUM_HORIZONS - 1
    main_kept = float(keep_mask[:, main_idx].mean())
    main_removed = 1.0 - main_kept
    print(
        f"[dir-mask] main horizon {HORIZONS_MS[main_idx]}ms kept={main_kept:.2%}, removed={main_removed:.2%}"
    )

    none_kept = float((~keep_mask.any(axis=1)).mean())
    all_kept = float((keep_mask.all(axis=1)).mean())
    print(f"[dir-mask] row sanity: none_kept={none_kept:.2%}, all_kept={all_kept:.2%}")

    return (
        pos_lo_arr,
        pos_hi_arr,
        neg_lo_arr,
        neg_hi_arr,
    )

def make_build_directional_noise_filter_mask_torch(pos_lo, pos_hi, neg_lo, neg_hi):
    # Build a label-space noise filter mask (mid-quantile magnitude keeper), not an SSL token mask.
    pos_lo_t = torch.from_numpy(pos_lo)
    pos_hi_t = torch.from_numpy(pos_hi)
    neg_lo_t = torch.from_numpy(neg_lo)
    neg_hi_t = torch.from_numpy(neg_hi)

    def build_directional_noise_filter_mask(y_ret: torch.Tensor) -> torch.Tensor:
        pos = y_ret > 0
        neg = y_ret < 0
        lo_pos = pos_lo_t.to(device=y_ret.device, dtype=y_ret.dtype).view(1, -1)
        hi_pos = pos_hi_t.to(device=y_ret.device, dtype=y_ret.dtype).view(1, -1)
        lo_neg = neg_lo_t.to(device=y_ret.device, dtype=y_ret.dtype).view(1, -1)
        hi_neg = neg_hi_t.to(device=y_ret.device, dtype=y_ret.dtype).view(1, -1)
        mag_neg = (-y_ret).clamp_min(0.0)
        keep_pos = pos & (y_ret >= lo_pos) & (y_ret <= hi_pos)
        keep_neg = neg & (mag_neg >= lo_neg) & (mag_neg <= hi_neg)
        return keep_pos | keep_neg
    return build_directional_noise_filter_mask

def compute_directional_loss_fn(build_directional_noise_filter_mask_fn, horizon_weights: torch.Tensor):
    def compute_directional_loss(logits: torch.Tensor, y_ret: torch.Tensor) -> torch.Tensor:
        noise_filter_mask = build_directional_noise_filter_mask_fn(y_ret)
        if not noise_filter_mask.any():
            return torch.tensor(0.0, device=logits.device)
        y_dir = (y_ret > 0).float()
        losses = []
        weights = []
        for h_idx in range(NUM_HORIZONS):
            noise_filter_mask_h = noise_filter_mask[:, h_idx]
            if noise_filter_mask_h.any():
                loss_h = F.binary_cross_entropy_with_logits(
                    logits[noise_filter_mask_h, h_idx], y_dir[noise_filter_mask_h, h_idx], reduction='mean'
                )
                losses.append(loss_h)
                weights.append(horizon_weights[h_idx])
        if not losses:
            return torch.tensor(0.0, device=logits.device)
        loss_stack = torch.stack(losses)
        weight_stack = torch.stack(weights)
        return (loss_stack * weight_stack).sum() / weight_stack.sum()
    return compute_directional_loss

# ---------------- Train/Eval ----------------
def train_from_offline():
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    amp_enabled = AMP_ENABLED and device.type == "cuda"
    amp_dtype = torch.bfloat16
    print(f"[amp] enabled={amp_enabled} dtype=bf16")
    out_root = Path(OUT_ROOT)
    meta = load_global_meta(out_root)
    splits = require_complete_splits(meta)

    pca_info = meta.get("pca", {}) or {}
    if pca_info:
        applied = bool(pca_info.get("applied", False))
        summary_parts = [f"applied={applied}"]
        var_kept = pca_info.get("var_kept")
        if isinstance(var_kept, (int, float)):
            summary_parts.append(f"var_kept={float(var_kept):.4f}")
        elif var_kept is not None:
            summary_parts.append(f"var_kept={var_kept}")
        k = pca_info.get("k")
        if k is not None:
            try:
                summary_parts.append(f"k={int(k)}")
            except (TypeError, ValueError):
                summary_parts.append(f"k={k}")
        model_path = pca_info.get("model_path")
        if model_path:
            summary_parts.append(f"model={model_path}")
        print(f"[pca-meta] {' '.join(summary_parts)}")
        if not applied:
            print("[warn] PCA metadata indicates the dataset was not reduced; training will use original feature dimensionality.")

    split_defs = splits["splits"]
    weeks_order = splits["weeks_in_order"]
    split_ranges = splits["split_ranges"]
    weeks_meta_map = meta.get("weeks_meta", {})

    key_to_meta: Dict[str, Path] = {}
    if weeks_meta_map and weeks_order:
        key_to_meta = {
            wk: out_root / weeks_meta_map[wk]
            for wk in weeks_order
            if wk in weeks_meta_map
        }

    if not key_to_meta:
        raise KeyError("meta must include non-empty 'weeks_in_order' and 'weeks_meta' for split week-key mapping")

    def keys_to_paths(keys: List[str], split_name: str) -> List[Path]:
        missing = [k for k in keys if k not in key_to_meta]
        if missing:
            raise KeyError(f"Split '{split_name}' references unknown week key(s): {missing}")
        return [key_to_meta[k] for k in keys]

    tr_weeks = keys_to_paths(split_defs["train"], "train")
    va_weeks = keys_to_paths(split_defs["val"], "val")
    te_weeks = keys_to_paths(split_defs["test"], "test")

    if not (tr_weeks and va_weeks and te_weeks):
        raise ValueError("Split metadata must resolve to at least one week for train/val/test")

    print(f"[weeks] train={len(tr_weeks)} val={len(va_weeks)} test={len(te_weeks)}")

    early_stop_patience = SINGLE_WEEK_PATIENCE if len(tr_weeks) <= 1 else PATIENCE
    if early_stop_patience != PATIENCE:
        print(f"[early-stop] using short patience={early_stop_patience} for single-week training")


    # feature dim sanity
    feat_dim_total = None
    for wp in tr_weeks + va_weeks + te_weeks:
        fm = int(read_json(wp)["feature_dim_total"])
        if feat_dim_total is None:
            feat_dim_total = fm
        elif feat_dim_total != fm:
            raise ValueError(f"Feature dim mismatch: saw {feat_dim_total} then {fm}")
    F_total = int(feat_dim_total or 0)

    # ---- build datasets or fully load ----
    tr_start, tr_end = split_ranges["train"]
    va_start, va_end = split_ranges["val"]
    te_start, te_end = split_ranges["test"]

    if USE_IN_MEMORY:
        X_tr, y_tr, feat_dim1 = load_split_in_memory_ts(tr_weeks, tr_start, tr_end)
        X_va, y_va, feat_dim2 = load_split_in_memory_ts(va_weeks, va_start, va_end)
        X_te, y_te, feat_dim3 = load_split_in_memory_ts(te_weeks, te_start, te_end)
        assert feat_dim1 == feat_dim2 == feat_dim3 == F_total, "feat dim mismatch"
        print(
            f"[offline-split-ts] train=[{tr_start},{tr_end}) N={len(y_tr)} "
            f"val=[{va_start},{va_end}) N={len(y_va)} test=[{te_start},{te_end}) N={len(y_te)}"
        )

        # Build in-RAM datasets
        ds_train = HFTDataset(X_tr, y_tr)
        ds_val   = HFTDataset(X_va, y_va)
        ds_test  = HFTDataset(X_te, y_te)
        print(
            f"[offline-data] train N={len(ds_train)}, "
            f"val N={len(ds_val)}, test N={len(ds_test)}"
        )
        # we still need y_tr to build directional mask quantiles
        y_train_for_quant = y_tr

    else:
        def refs_for_weeks_timerange(weeks: List[Path], start: int, end: int) -> List[ChunkRef]:
            refs: List[ChunkRef] = []
            for wp in weeks:
                refs.extend(build_chunk_refs_by_ts(wp, start, end))
            return refs

        tr_refs = refs_for_weeks_timerange(tr_weeks, tr_start, tr_end)
        va_refs = refs_for_weeks_timerange(va_weeks, va_start, va_end)
        te_refs = refs_for_weeks_timerange(te_weeks, te_start, te_end)
        print(
            f"[offline-split-ts] train=[{tr_start},{tr_end}) N={sum(r.n for r in tr_refs)} "
            f"val=[{va_start},{va_end}) N={sum(r.n for r in va_refs)} "
            f"test=[{te_start},{te_end}) N={sum(r.n for r in te_refs)}"
        )

        ds_train = NpyChunksDataset(tr_refs, F_total)
        ds_val   = NpyChunksDataset(va_refs, F_total)
        ds_test  = NpyChunksDataset(te_refs, F_total)
        print(
            f"[offline-data] train N={len(ds_train)}, "
            f"val N={len(ds_val)}, test N={len(ds_test)}"
        )

        # Build y_train_for_quant without loading features into RAM
        if len(ds_train) == 0:
            y_train_for_quant = np.empty((0, 2 * NUM_HORIZONS), dtype=np.float32)
        else:
            dl_prepass = DataLoader(
                ds_train,
                batch_size=BATCH_SIZE,
                shuffle=False,
                drop_last=False,
                num_workers=WORKERS_TRAIN,
                pin_memory=True,
            )
            y_parts: List[np.ndarray] = []
            with torch.no_grad():
                for _, y_batch in tqdm(dl_prepass, desc="[prepass y_train quantiles]"):
                    y_parts.append(y_batch.numpy())
            y_train_for_quant = (
                np.concatenate(y_parts, axis=0)
                if y_parts
                else np.empty((0, 2 * NUM_HORIZONS), dtype=np.float32)
            )


    # ---------------- directional-noise filter quantiles & loss closure ----------------
    pos_lo, pos_hi, neg_lo, neg_hi = compute_dir_mask_quantiles_from_ytrain(y_train_for_quant)
    build_directional_noise_filter_mask = make_build_directional_noise_filter_mask_torch(pos_lo, pos_hi, neg_lo, neg_hi)
    horizon_weights = torch.tensor(HORIZON_WEIGHTS, dtype=torch.float32, device=device)
    horizon_weights_cpu = horizon_weights.detach().cpu().to(torch.float64)
    horizon_weights_np = horizon_weights_cpu.numpy()
    delta_ret_tensor = torch.as_tensor(DELTA_RET, dtype=torch.float32, device=device)
    delta_logvol_tensor = torch.as_tensor(DELTA_LOGVOL, dtype=torch.float32, device=device)
    compute_directional_loss = compute_directional_loss_fn(build_directional_noise_filter_mask, horizon_weights)

    def compute_masked_regression_loss(
        pred: torch.Tensor,
        target: torch.Tensor,
        delta: torch.Tensor,
        noise_filter_mask: torch.Tensor,
        weights: torch.Tensor,
    ) -> torch.Tensor:
        if not noise_filter_mask.any():
            return torch.tensor(0.0, device=pred.device)
        loss_elem = huber_loss(pred, target, delta, reduction='none')
        losses = []
        weight_list = []
        for h_idx in range(NUM_HORIZONS):
            noise_filter_mask_h = noise_filter_mask[:, h_idx]
            if noise_filter_mask_h.any():
                loss_h = loss_elem[noise_filter_mask_h, h_idx].mean()
                losses.append(loss_h)
                weight_list.append(weights[h_idx])
        if not losses:
            return torch.tensor(0.0, device=pred.device)
        loss_stack = torch.stack(losses)
        weight_stack = torch.stack(weight_list)
        return (loss_stack * weight_stack).sum() / weight_stack.sum()

    def format_metric(values: Iterable[float], fmt: str) -> str:
        formatted = []
        for horizon, value in zip(HORIZONS_MS, values):
            val = float(value)
            if math.isnan(val) or math.isinf(val):
                formatted.append(f"{horizon}ms:nan")
            else:
                formatted.append(f"{horizon}ms:{fmt.format(val)}")
        return '[' + ', '.join(formatted) + ']'

    # ---------------- DataLoaders ----------------
    dl_train = DataLoader(
        ds_train,
        BATCH_SIZE,
        shuffle=True,
        drop_last=True,
        num_workers=WORKERS_TRAIN,
        pin_memory=True,
        prefetch_factor=8 if WORKERS_TRAIN > 0 else None,
        persistent_workers=(WORKERS_TRAIN > 0),
    )
    dl_val = DataLoader(
        ds_val,
        BATCH_SIZE,
        shuffle=False,
        num_workers=max(1, WORKERS_VAL),
        pin_memory=True,
        persistent_workers=(max(1, WORKERS_VAL) > 0),
    )
    dl_test = DataLoader(
        ds_test,
        BATCH_SIZE,
        shuffle=False,
        num_workers=max(1, WORKERS_VAL),
        pin_memory=True,
        persistent_workers=(max(1, WORKERS_VAL) > 0),
    )

    # ---------------- Model ----------------
    args = ModelArgs(DMODEL, MAMBA_LAYERS, F_total, LOOKBACK)
    model = SAMBA(args).to(device)
    primary_metric_mode = get_primary_metric_mode()
    opt = SAM(model.parameters(), torch.optim.AdamW, lr=LR, weight_decay=1e-3, rho=0.01)
    torch.cuda.empty_cache()

    # ---------------- Epoch loop ----------------
    best = -float('inf') if primary_metric_mode == "max" else float('inf')
    no_imp = 0
    ema_ft  = {
        'ret': 1.0,
        'logvol': 1.0,
        'ret_masked': 1.0,
        'logvol_masked': 1.0,
        'bce': 1.0,
    }
    primary_horizon_idx = HORIZONS_MS.index(PRIMARY_METRIC_HORIZON_MS)

    def run_validation(*, primary_horizon_idx: int, full_metrics: bool) -> dict:
        model.eval()
        with torch.no_grad():
            if not full_metrics:
                primary_ret_masked_sum = 0.0
                primary_ret_masked_count = 0.0
                primary_vol_masked_sum = 0.0
                primary_vol_masked_count = 0.0
                primary_logits_masked: List[torch.Tensor] = []
                primary_targets_masked: List[torch.Tensor] = []
                primary_acc_masked_sum = 0.0
                primary_masked_total = 0.0

                for x, y_targets in dl_val:
                    x = x.to(device, non_blocking=True)
                    y_targets = y_targets.to(device, non_blocking=True)
                    y_return = y_targets[:, :NUM_HORIZONS]
                    y_logvol = y_targets[:, NUM_HORIZONS:2 * NUM_HORIZONS]

                    with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=amp_enabled):
                        ret_pred, vol_pred, dir_pred_logits = model(x)
                        ret_loss_elem = huber_loss(ret_pred, y_return, delta_ret_tensor, reduction='none')
                        vol_loss_elem = huber_loss(vol_pred, y_logvol, delta_logvol_tensor, reduction='none')
                        y_dir = (y_return > 0).to(torch.float32)

                    ret_loss_elem = ret_loss_elem.float()
                    vol_loss_elem = vol_loss_elem.float()
                    dir_pred_logits = dir_pred_logits.float()

                    noise_filter_mask = build_directional_noise_filter_mask(y_return)
                    primary_mask = noise_filter_mask[:, primary_horizon_idx]
                    if primary_mask.any():
                        primary_ret = ret_loss_elem[primary_mask, primary_horizon_idx]
                        primary_vol = vol_loss_elem[primary_mask, primary_horizon_idx]
                        primary_logits = dir_pred_logits[primary_mask, primary_horizon_idx]
                        primary_targets = y_dir[primary_mask, primary_horizon_idx]

                        primary_ret_masked_sum += primary_ret.sum().item()
                        primary_ret_masked_count += primary_mask.sum().item()
                        primary_vol_masked_sum += primary_vol.sum().item()
                        primary_vol_masked_count += primary_mask.sum().item()
                        primary_logits_masked.append(primary_logits.detach().cpu())
                        primary_targets_masked.append(primary_targets.to(torch.int32).detach().cpu())
                        primary_acc_masked_sum += (
                            (primary_logits > 0).to(torch.int32) == primary_targets.to(torch.int32)
                        ).sum().item()
                        primary_masked_total += primary_mask.sum().item()

                primary_masked_ret_loss = (
                    float(primary_ret_masked_sum / primary_ret_masked_count)
                    if primary_ret_masked_count > 0
                    else float('nan')
                )
                primary_masked_vol_loss = (
                    float(primary_vol_masked_sum / primary_vol_masked_count)
                    if primary_vol_masked_count > 0
                    else float('nan')
                )
                primary_masked_auc = float('nan')
                if primary_logits_masked:
                    logits_cat = torch.cat(primary_logits_masked, dim=0).view(-1)
                    targets_cat = torch.cat(primary_targets_masked, dim=0).view(-1)
                    primary_masked_auc = binary_auc_from_logits(logits_cat, targets_cat)
                primary_masked_acc = (
                    float(primary_acc_masked_sum / primary_masked_total)
                    if primary_masked_total > 0
                    else float('nan')
                )

                val_auc_masked = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
                val_ret_loss_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
                val_vol_loss_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
                val_auc_masked[primary_horizon_idx] = primary_masked_auc
                val_ret_loss_masked_per_h[primary_horizon_idx] = primary_masked_ret_loss
                val_vol_loss_masked_per_h[primary_horizon_idx] = primary_masked_vol_loss

                primary_metric_value, primary_metric_label = compute_primary_metric(
                    val_auc_masked,
                    val_ret_loss_masked_per_h,
                    val_vol_loss_masked_per_h,
                )
                return {
                    "primary_metric_value": float(primary_metric_value),
                    "primary_metric_label": primary_metric_label,
                    "primary_masked_ret_loss": primary_masked_ret_loss,
                    "primary_masked_vol_loss": primary_masked_vol_loss,
                    "primary_masked_auc": primary_masked_auc,
                    "primary_masked_acc": primary_masked_acc,
                }

            val_ret_loss_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_vol_loss_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_ret_loss_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_ret_loss_masked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_vol_loss_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_vol_loss_masked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_sample_total = 0
            val_acc_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_total   = 0

            val_bce_unmasked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_bce_unmasked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_bce_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_bce_masked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_acc_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
            val_masked_total = np.zeros(NUM_HORIZONS, dtype=np.float64)

            val_logits_all = [[] for _ in range(NUM_HORIZONS)]
            val_ypos_all   = [[] for _ in range(NUM_HORIZONS)]
            val_logits_masked = [[] for _ in range(NUM_HORIZONS)]
            val_ypos_masked   = [[] for _ in range(NUM_HORIZONS)]

            for x, y_targets in dl_val:
                x = x.to(device, non_blocking=True)
                y_targets = y_targets.to(device, non_blocking=True)
                y_return = y_targets[:, :NUM_HORIZONS]
                y_logvol = y_targets[:, NUM_HORIZONS:2 * NUM_HORIZONS]

                with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=amp_enabled):
                    ret_pred, vol_pred, dir_pred_logits = model(x)
                    ret_loss_elem = huber_loss(ret_pred, y_return, delta_ret_tensor, reduction='none')
                    vol_loss_elem = huber_loss(vol_pred, y_logvol, delta_logvol_tensor, reduction='none')
                    y_dir = (y_return > 0).to(torch.float32)
                    bce_elem = F.binary_cross_entropy_with_logits(dir_pred_logits, y_dir, reduction='none')

                ret_loss_elem = ret_loss_elem.float()
                vol_loss_elem = vol_loss_elem.float()
                dir_pred_logits = dir_pred_logits.float()
                bce_elem = bce_elem.float()

                batch_n = x.size(0)

                val_ret_loss_sum += ret_loss_elem.sum(dim=0).detach().cpu().numpy().astype(np.float64)
                val_vol_loss_sum += vol_loss_elem.sum(dim=0).detach().cpu().numpy().astype(np.float64)
                val_sample_total += batch_n

                val_bce_unmasked_sum += bce_elem.sum(dim=0).detach().cpu().numpy().astype(np.float64)
                val_bce_unmasked_count += batch_n

                pred_class = (dir_pred_logits > 0).to(torch.int32)
                true_class = y_dir.to(torch.int32)
                val_acc_sum += (pred_class == true_class).sum(dim=0).detach().cpu().numpy().astype(np.float64)
                val_total += batch_n

                for h_idx in range(NUM_HORIZONS):
                    val_logits_all[h_idx].append(dir_pred_logits[:, h_idx].detach().cpu())
                    val_ypos_all[h_idx].append(true_class[:, h_idx].detach().cpu())

                noise_filter_mask = build_directional_noise_filter_mask(y_return)
                for h_idx in range(NUM_HORIZONS):
                    noise_filter_mask_h = noise_filter_mask[:, h_idx]
                    if noise_filter_mask_h.any():
                        ret_masked_h = ret_loss_elem[noise_filter_mask_h, h_idx]
                        vol_masked_h = vol_loss_elem[noise_filter_mask_h, h_idx]
                        val_ret_loss_masked_sum[h_idx] += ret_masked_h.sum().item()
                        val_ret_loss_masked_count[h_idx] += noise_filter_mask_h.sum().item()
                        val_vol_loss_masked_sum[h_idx] += vol_masked_h.sum().item()
                        val_vol_loss_masked_count[h_idx] += noise_filter_mask_h.sum().item()
                        logits_h = dir_pred_logits[noise_filter_mask_h, h_idx]
                        targets_h = y_dir[noise_filter_mask_h, h_idx]
                        val_bce_masked_sum[h_idx] += F.binary_cross_entropy_with_logits(
                            logits_h, targets_h, reduction='sum'
                        ).item()
                        val_bce_masked_count[h_idx] += noise_filter_mask_h.sum().item()
                        val_logits_masked[h_idx].append(logits_h.detach().cpu())
                        val_ypos_masked[h_idx].append(targets_h.to(torch.int32).detach().cpu())
                        val_acc_masked_sum[h_idx] += ((logits_h > 0).to(torch.int32) == targets_h.to(torch.int32)).sum().item()
                        val_masked_total[h_idx] += noise_filter_mask_h.sum().item()

        avg_val_ret_loss_per_h = val_ret_loss_sum / max(val_sample_total, 1)
        avg_val_vol_loss_per_h = val_vol_loss_sum / max(val_sample_total, 1)
        val_ret_loss_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        val_vol_loss_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        ret_masked_valid = val_ret_loss_masked_count > 0
        vol_masked_valid = val_vol_loss_masked_count > 0
        val_ret_loss_masked_per_h[ret_masked_valid] = (
            val_ret_loss_masked_sum[ret_masked_valid] / val_ret_loss_masked_count[ret_masked_valid]
        )
        val_vol_loss_masked_per_h[vol_masked_valid] = (
            val_vol_loss_masked_sum[vol_masked_valid] / val_vol_loss_masked_count[vol_masked_valid]
        )
        avg_val_ret_loss = float(
            np.dot(avg_val_ret_loss_per_h, horizon_weights_np)
            / max(horizon_weights_cpu.sum().item(), 1e-12)
        )
        avg_val_vol_loss = float(
            np.dot(avg_val_vol_loss_per_h, horizon_weights_np)
            / max(horizon_weights_cpu.sum().item(), 1e-12)
        )
        ret_masked_weights = horizon_weights_np[ret_masked_valid]
        vol_masked_weights = horizon_weights_np[vol_masked_valid]
        avg_val_ret_loss_masked = float(
            np.dot(val_ret_loss_masked_per_h[ret_masked_valid], ret_masked_weights)
            / max(ret_masked_weights.sum(), 1e-12)
        ) if ret_masked_weights.size else float('nan')
        avg_val_vol_loss_masked = float(
            np.dot(val_vol_loss_masked_per_h[vol_masked_valid], vol_masked_weights)
            / max(vol_masked_weights.sum(), 1e-12)
        ) if vol_masked_weights.size else float('nan')

        val_bce_unmasked = val_bce_unmasked_sum / np.maximum(val_bce_unmasked_count, 1)
        val_bce_masked = val_bce_masked_sum / np.maximum(val_bce_masked_count, 1)
        val_acc = val_acc_sum / np.maximum(val_total, 1)
        val_acc_masked = val_acc_masked_sum / np.maximum(val_masked_total, 1)

        val_auc = np.zeros(NUM_HORIZONS, dtype=np.float64)
        val_auc_masked = np.zeros(NUM_HORIZONS, dtype=np.float64)
        val_pos_rate_all = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        val_logit_mean_all = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        val_logit_std_all = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        val_pos_rate_masked = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        val_logit_mean_masked = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        val_logit_std_masked = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
        for h_idx in range(NUM_HORIZONS):
            if val_logits_all[h_idx]:
                logits_cat = torch.cat(val_logits_all[h_idx], dim=0).view(-1)
                ypos_cat = torch.cat(val_ypos_all[h_idx], dim=0).view(-1)
                val_auc[h_idx] = binary_auc_from_logits(logits_cat, ypos_cat)
                val_pos_rate_all[h_idx] = float(ypos_cat.float().mean().item())
                val_logit_mean_all[h_idx] = float(logits_cat.mean().item())
                val_logit_std_all[h_idx] = float(logits_cat.std(unbiased=False).item())
            else:
                val_auc[h_idx] = float('nan')
            if val_logits_masked[h_idx]:
                logits_cat = torch.cat(val_logits_masked[h_idx], dim=0).view(-1)
                ypos_cat = torch.cat(val_ypos_masked[h_idx], dim=0).view(-1)
                val_auc_masked[h_idx] = binary_auc_from_logits(logits_cat, ypos_cat)
                val_pos_rate_masked[h_idx] = float(ypos_cat.float().mean().item())
                val_logit_mean_masked[h_idx] = float(logits_cat.mean().item())
                val_logit_std_masked[h_idx] = float(logits_cat.std(unbiased=False).item())
            else:
                val_auc_masked[h_idx] = float('nan')

        primary_metric_value, primary_metric_label = compute_primary_metric(
            val_auc_masked,
            val_ret_loss_masked_per_h,
            val_vol_loss_masked_per_h,
        )

        return {
            "avg_val_ret_loss_per_h": avg_val_ret_loss_per_h,
            "avg_val_vol_loss_per_h": avg_val_vol_loss_per_h,
            "avg_val_ret_loss": avg_val_ret_loss,
            "avg_val_vol_loss": avg_val_vol_loss,
            "val_ret_loss_masked_per_h": val_ret_loss_masked_per_h,
            "val_vol_loss_masked_per_h": val_vol_loss_masked_per_h,
            "avg_val_ret_loss_masked": avg_val_ret_loss_masked,
            "avg_val_vol_loss_masked": avg_val_vol_loss_masked,
            "val_bce_unmasked": val_bce_unmasked,
            "val_bce_masked": val_bce_masked,
            "val_acc": val_acc,
            "val_acc_masked": val_acc_masked,
            "val_auc": val_auc,
            "val_auc_masked": val_auc_masked,
            "val_pos_rate_all": val_pos_rate_all,
            "val_logit_mean_all": val_logit_mean_all,
            "val_logit_std_all": val_logit_std_all,
            "val_pos_rate_masked": val_pos_rate_masked,
            "val_logit_mean_masked": val_logit_mean_masked,
            "val_logit_std_masked": val_logit_std_masked,
            "primary_metric_value": float(primary_metric_value),
            "primary_metric_label": primary_metric_label,
            "primary_masked_ret_loss": float(val_ret_loss_masked_per_h[primary_horizon_idx]),
            "primary_masked_vol_loss": float(val_vol_loss_masked_per_h[primary_horizon_idx]),
            "primary_masked_auc": float(val_auc_masked[primary_horizon_idx]),
        }

    for epoch in range(EPOCHS):
        early_stop_triggered = False
        model.train()
        pbar = tqdm(dl_train, desc=f"Ep{epoch+1}/{EPOCHS}")
        num_train_batches = len(dl_train)
        running_loss_t = torch.zeros((), device=device, dtype=torch.float32)
        running_ret_t = torch.zeros((), device=device, dtype=torch.float32)
        running_vol_t = torch.zeros((), device=device, dtype=torch.float32)
        running_ret_masked_t = torch.zeros((), device=device, dtype=torch.float32)
        running_vol_masked_t = torch.zeros((), device=device, dtype=torch.float32)
        running_bce_t = torch.zeros((), device=device, dtype=torch.float32)
        n_batches = 0

        for batch_idx, (x, y) in enumerate(pbar):
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)

            y_ret = y[:, :NUM_HORIZONS]
            y_logvol = y[:, NUM_HORIZONS:2 * NUM_HORIZONS]

            # ===== SAM pass #1 =====
            opt.base_optimizer.zero_grad(set_to_none=True)
            with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=amp_enabled):
                ret_pred, vol_pred, dir_pred_logits = model(x)
                mse_ret = huber_loss(ret_pred, y_ret, delta_ret_tensor, weights=horizon_weights)
                mse_vol = huber_loss(vol_pred, y_logvol, delta_logvol_tensor, weights=horizon_weights)
                noise_filter_mask = build_directional_noise_filter_mask(y_ret)
                mse_ret_masked = compute_masked_regression_loss(
                    ret_pred, y_ret, delta_ret_tensor, noise_filter_mask, horizon_weights
                )
                mse_vol_masked = compute_masked_regression_loss(
                    vol_pred, y_logvol, delta_logvol_tensor, noise_filter_mask, horizon_weights
                )
                bce_loss = compute_directional_loss(dir_pred_logits, y_ret)
                loss = (
                    LAMBDA_RET * (mse_ret_masked / (ema_ft['ret_masked'] + 1e-8)) +
                    LAMBDA_VOL * (mse_vol_masked / (ema_ft['logvol_masked'] + 1e-8)) +
                    LAMBDA_BCE * (bce_loss / (ema_ft['bce'] + 1e-8))
                )

            if not torch.isfinite(loss):
                raise RuntimeError(
                    f"Non-finite training loss in SAM pass #1: {float(loss.detach().float().cpu())}"
                )

            ema_ret_masked = ema_update('ret_masked', float(mse_ret_masked.detach().float().cpu()), ema_ft)
            ema_logvol_masked = ema_update('logvol_masked', float(mse_vol_masked.detach().float().cpu()), ema_ft)
            ema_bce = ema_update('bce', float(bce_loss.detach().float().cpu()), ema_ft)

            # recompute normalized loss after EMA update, still under autocast-style tensor types
            with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=amp_enabled):
                loss = (
                    LAMBDA_RET * (mse_ret_masked / (ema_ret_masked + 1e-8)) +
                    LAMBDA_VOL * (mse_vol_masked / (ema_logvol_masked + 1e-8)) +
                    LAMBDA_BCE * (bce_loss / (ema_bce + 1e-8))
                )

            running_ret_t += mse_ret.detach().float()
            running_vol_t += mse_vol.detach().float()
            running_ret_masked_t += mse_ret_masked.detach().float()
            running_vol_masked_t += mse_vol_masked.detach().float()
            running_bce_t += bce_loss.detach().float()

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 10_000)
            opt.first_step(zero_grad=True)

            # ===== SAM pass #2 =====
            with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=amp_enabled):
                ret_pred2, vol_pred2, dir_pred_logits2 = model(x)
                mse_ret2 = huber_loss(ret_pred2, y_ret, delta_ret_tensor, weights=horizon_weights)
                mse_vol2 = huber_loss(vol_pred2, y_logvol, delta_logvol_tensor, weights=horizon_weights)
                noise_filter_mask2 = build_directional_noise_filter_mask(y_ret)
                mse_ret2_masked = compute_masked_regression_loss(
                    ret_pred2, y_ret, delta_ret_tensor, noise_filter_mask2, horizon_weights
                )
                mse_vol2_masked = compute_masked_regression_loss(
                    vol_pred2, y_logvol, delta_logvol_tensor, noise_filter_mask2, horizon_weights
                )
                bce_loss2 = compute_directional_loss(dir_pred_logits2, y_ret)
                loss2 = (
                    LAMBDA_RET * (mse_ret2_masked / (ema_ft['ret_masked'] + 1e-8)) +
                    LAMBDA_VOL * (mse_vol2_masked / (ema_ft['logvol_masked'] + 1e-8)) +
                    LAMBDA_BCE * (bce_loss2 / (ema_ft['bce'] + 1e-8))
                )

            if not torch.isfinite(loss2):
                raise RuntimeError(
                    f"Non-finite training loss in SAM pass #2: {float(loss2.detach().float().cpu())}"
                )

            loss2.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 10_000)
            opt.second_step(zero_grad=True)

            running_loss_t += loss.detach().float()
            n_batches += 1
            should_log_batch = ((batch_idx + 1) % LOG_EVERY == 0) or ((batch_idx + 1) == num_train_batches)
            if should_log_batch:
                denom = float(max(1, n_batches))
                running_loss = float(running_loss_t.detach().cpu())
                running_ret = float(running_ret_t.detach().cpu())
                running_vol = float(running_vol_t.detach().cpu())
                running_ret_masked = float(running_ret_masked_t.detach().cpu())
                running_vol_masked = float(running_vol_masked_t.detach().cpu())
                running_bce = float(running_bce_t.detach().cpu())

                pbar.set_postfix(
                    loss=f"{(running_loss / denom):.4f}",
                    ret=f"{(running_ret / denom):.4f}",
                    vol=f"{(running_vol / denom):.4f}",
                    ret_m=f"{(running_ret_masked / denom):.4f}",
                    vol_m=f"{(running_vol_masked / denom):.4f}",
                    bce=f"{(running_bce / denom):.4f}",
                )

        epoch_train_loss = float(running_loss_t.detach().cpu()) / float(max(1, n_batches))
        epoch_train_ret = float(running_ret_t.detach().cpu()) / float(max(1, n_batches))
        epoch_train_vol = float(running_vol_t.detach().cpu()) / float(max(1, n_batches))
        epoch_train_ret_masked = float(running_ret_masked_t.detach().cpu()) / float(max(1, n_batches))
        epoch_train_vol_masked = float(running_vol_masked_t.detach().cpu()) / float(max(1, n_batches))
        epoch_train_bce = float(running_bce_t.detach().cpu()) / float(max(1, n_batches))
        print(
            f"[train] loss={epoch_train_loss:.4f} ret={epoch_train_ret:.4f} vol={epoch_train_vol:.4f} "
            f"ret(mask)={epoch_train_ret_masked:.4f} vol(mask)={epoch_train_vol_masked:.4f} bce={epoch_train_bce:.4f}"
        )

        # ---------------- Validation ----------------
        fast_val = run_validation(primary_horizon_idx=primary_horizon_idx, full_metrics=False)
        primary_metric_value = float(fast_val["primary_metric_value"])
        primary_metric_label = str(fast_val["primary_metric_label"])

        if math.isfinite(primary_metric_value):
            print(
                f"[val-fast] primary_metric({primary_metric_label})={primary_metric_value:.6f} "
                f"[masked_ret_loss_{PRIMARY_METRIC_HORIZON_MS}ms={float(fast_val['primary_masked_ret_loss']):.6f}, "
                f"masked_vol_loss_{PRIMARY_METRIC_HORIZON_MS}ms={float(fast_val['primary_masked_vol_loss']):.6f}, "
                f"masked_auc_{PRIMARY_METRIC_HORIZON_MS}ms={float(fast_val['primary_masked_auc']):.6f}, "
                f"masked_acc_{PRIMARY_METRIC_HORIZON_MS}ms={float(fast_val['primary_masked_acc']):.3%}]"
            )
            if is_metric_improved(primary_metric_value, best, primary_metric_mode):
                best = float(primary_metric_value)
                no_imp = 0
                full_val = run_validation(primary_horizon_idx=primary_horizon_idx, full_metrics=True)
                print(
                    f"[val] ret={format_metric(full_val['avg_val_ret_loss_per_h'], '{:.5f}')} "
                    f"(w_avg={float(full_val['avg_val_ret_loss']):.4e})  "
                    f"vol={format_metric(full_val['avg_val_vol_loss_per_h'], '{:.5f}')} "
                    f"(w_avg={float(full_val['avg_val_vol_loss']):.4e})  "
                    f"ret(mask)={format_metric(full_val['val_ret_loss_masked_per_h'], '{:.5f}')} "
                    f"(w_avg={float(full_val['avg_val_ret_loss_masked']):.4e})  "
                    f"vol(mask)={format_metric(full_val['val_vol_loss_masked_per_h'], '{:.5f}')} "
                    f"(w_avg={float(full_val['avg_val_vol_loss_masked']):.4e})  "
                    f"BCE(all)={format_metric(full_val['val_bce_unmasked'], '{:.5f}')}  "
                    f"BCE(mask)={format_metric(full_val['val_bce_masked'], '{:.5f}')}  "
                    f"Acc(all)={format_metric(full_val['val_acc'], '{:.3%}')}  "
                    f"Acc(mask)={format_metric(full_val['val_acc_masked'], '{:.3%}')}  "
                    f"AUC(all)={format_metric(full_val['val_auc'], '{:.3f}')}  "
                    f"AUC(mask)={format_metric(full_val['val_auc_masked'], '{:.3f}')}")
                print(
                    f"[val_diag] pos_rate(all)={format_metric(full_val['val_pos_rate_all'], '{:.3%}')}  "
                    f"logit_mean(all)={format_metric(full_val['val_logit_mean_all'], '{:.3f}')}  "
                    f"logit_std(all)={format_metric(full_val['val_logit_std_all'], '{:.3f}')}  "
                    f"pos_rate(mask)={format_metric(full_val['val_pos_rate_masked'], '{:.3%}')}  "
                    f"logit_mean(mask)={format_metric(full_val['val_logit_mean_masked'], '{:.3f}')}  "
                    f"logit_std(mask)={format_metric(full_val['val_logit_std_masked'], '{:.3f}')}")
                print(
                    f"[val] primary_metric({primary_metric_label})={primary_metric_value:.6f} "
                    f"[masked_ret_loss_{PRIMARY_METRIC_HORIZON_MS}ms={float(full_val['primary_masked_ret_loss']):.6f}, "
                    f"masked_vol_loss_{PRIMARY_METRIC_HORIZON_MS}ms={float(full_val['primary_masked_vol_loss']):.6f}, "
                    f"masked_auc_{PRIMARY_METRIC_HORIZON_MS}ms={float(full_val['primary_masked_auc']):.6f}]"
                )
                ckpt = {
                    "epoch": epoch,
                    "state_dict": model.state_dict(),
                    "args": {
                        "DMODEL": DMODEL, "MAMBA_LAYERS": MAMBA_LAYERS,
                        "feat_dim": F_total, "LOOKBACK": LOOKBACK,
                        "HORIZONS_MS": HORIZONS_MS,
                    },
                    "best_primary_metric": best,
                }
                out_ckpt = out_root / "cmssl17_offline_best.pt"
                torch.save(ckpt, out_ckpt)
                print(f"[ckpt] saved best to {out_ckpt}")
            else:
                no_imp += 1
                print(f"no improve {no_imp}/{early_stop_patience}")
                if no_imp >= early_stop_patience:
                    print("Early stopping triggered.")
                    early_stop_triggered = True
        else:
            print(f"[val-fast] primary_metric({primary_metric_label})=nan (skipping early stop)")

        if early_stop_triggered:
            break

        # (Optional) early stop on long stagnation
        # if no_imp > 50: break

    # ---------------- Test Evaluation ----------------
    model.eval()
    test_ret_loss_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_vol_loss_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_ret_loss_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_ret_loss_masked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_vol_loss_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_vol_loss_masked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_sample_total = 0
    test_acc_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_total = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_bce_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_bce_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_bce_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_bce_masked_count = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_acc_masked_sum = np.zeros(NUM_HORIZONS, dtype=np.float64)
    test_masked_total = np.zeros(NUM_HORIZONS, dtype=np.float64)

    test_logits_all = [[] for _ in range(NUM_HORIZONS)]
    test_ypos_all = [[] for _ in range(NUM_HORIZONS)]
    test_logits_masked = [[] for _ in range(NUM_HORIZONS)]
    test_ypos_masked = [[] for _ in range(NUM_HORIZONS)]

    with torch.no_grad():
        for x, y in dl_test:
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            y_return = y[:, :NUM_HORIZONS]
            y_logvol = y[:, NUM_HORIZONS:2 * NUM_HORIZONS]

            with torch.amp.autocast("cuda", dtype=amp_dtype, enabled=amp_enabled):
                ret_pred, vol_pred, dir_pred_logits = model(x)
                ret_loss_elem = huber_loss(ret_pred, y_return, delta_ret_tensor, reduction='none')
                vol_loss_elem = huber_loss(vol_pred, y_logvol, delta_logvol_tensor, reduction='none')
                y_dir = (y_return > 0).to(torch.float32)
                bce_elem = F.binary_cross_entropy_with_logits(dir_pred_logits, y_dir, reduction='none')

            ret_loss_elem = ret_loss_elem.float()
            vol_loss_elem = vol_loss_elem.float()
            dir_pred_logits = dir_pred_logits.float()
            bce_elem = bce_elem.float()

            batch_n = x.size(0)

            test_ret_loss_sum += ret_loss_elem.sum(dim=0).detach().cpu().numpy().astype(np.float64)
            test_vol_loss_sum += vol_loss_elem.sum(dim=0).detach().cpu().numpy().astype(np.float64)
            test_sample_total += batch_n

            test_bce_sum += bce_elem.sum(dim=0).detach().cpu().numpy().astype(np.float64)
            test_bce_count += batch_n

            pred_class = (dir_pred_logits > 0).to(torch.int32)
            true_class = y_dir.to(torch.int32)
            test_acc_sum += (pred_class == true_class).sum(dim=0).detach().cpu().numpy().astype(np.float64)
            test_total += batch_n

            for h_idx in range(NUM_HORIZONS):
                test_logits_all[h_idx].append(dir_pred_logits[:, h_idx].detach().cpu())
                test_ypos_all[h_idx].append(true_class[:, h_idx].detach().cpu())

            noise_filter_mask = build_directional_noise_filter_mask(y_return)
            for h_idx in range(NUM_HORIZONS):
                noise_filter_mask_h = noise_filter_mask[:, h_idx]
                if noise_filter_mask_h.any():
                    ret_masked_h = ret_loss_elem[noise_filter_mask_h, h_idx]
                    vol_masked_h = vol_loss_elem[noise_filter_mask_h, h_idx]
                    test_ret_loss_masked_sum[h_idx] += ret_masked_h.sum().item()
                    test_ret_loss_masked_count[h_idx] += noise_filter_mask_h.sum().item()
                    test_vol_loss_masked_sum[h_idx] += vol_masked_h.sum().item()
                    test_vol_loss_masked_count[h_idx] += noise_filter_mask_h.sum().item()
                    logits_h = dir_pred_logits[noise_filter_mask_h, h_idx]
                    targets_h = y_dir[noise_filter_mask_h, h_idx]
                    test_bce_masked_sum[h_idx] += F.binary_cross_entropy_with_logits(
                        logits_h, targets_h, reduction='sum'
                    ).item()
                    test_bce_masked_count[h_idx] += noise_filter_mask_h.sum().item()
                    test_logits_masked[h_idx].append(logits_h.detach().cpu())
                    test_ypos_masked[h_idx].append(targets_h.to(torch.int32).detach().cpu())
                    test_acc_masked_sum[h_idx] += ((logits_h > 0).to(torch.int32) == targets_h.to(torch.int32)).sum().item()
                    test_masked_total[h_idx] += noise_filter_mask_h.sum().item()

    avg_test_ret_loss_per_h = test_ret_loss_sum / max(1, test_sample_total)
    avg_test_vol_loss_per_h = test_vol_loss_sum / max(1, test_sample_total)
    test_ret_loss_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
    test_vol_loss_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
    test_ret_masked_valid = test_ret_loss_masked_count > 0
    test_vol_masked_valid = test_vol_loss_masked_count > 0
    test_ret_loss_masked_per_h[test_ret_masked_valid] = (
        test_ret_loss_masked_sum[test_ret_masked_valid] / test_ret_loss_masked_count[test_ret_masked_valid]
    )
    test_vol_loss_masked_per_h[test_vol_masked_valid] = (
        test_vol_loss_masked_sum[test_vol_masked_valid] / test_vol_loss_masked_count[test_vol_masked_valid]
    )
    test_dir_bce_per_h = np.divide(test_bce_sum, np.maximum(test_bce_count, 1.0))
    test_accuracy_per_h = np.divide(test_acc_sum, np.maximum(test_total, 1.0))

    test_auc_per_h = []
    for h_idx in range(NUM_HORIZONS):
        if test_logits_all[h_idx]:
            logits_cat = torch.cat(test_logits_all[h_idx])
            ypos_cat = torch.cat(test_ypos_all[h_idx])
            test_auc_per_h.append(binary_auc_from_logits(logits_cat, ypos_cat))
        else:
            test_auc_per_h.append(float('nan'))

    test_dir_bce_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
    test_acc_masked_per_h = np.full(NUM_HORIZONS, np.nan, dtype=np.float64)
    test_auc_masked_per_h: List[float] = []
    for h_idx in range(NUM_HORIZONS):
        if test_bce_masked_count[h_idx] > 0:
            test_dir_bce_masked_per_h[h_idx] = test_bce_masked_sum[h_idx] / test_bce_masked_count[h_idx]
            test_acc_masked_per_h[h_idx] = test_acc_masked_sum[h_idx] / max(test_masked_total[h_idx], 1.0)
            logits_cat = torch.cat(test_logits_masked[h_idx])
            ypos_cat = torch.cat(test_ypos_masked[h_idx])
            test_auc_masked_per_h.append(binary_auc_from_logits(logits_cat, ypos_cat))
        else:
            test_auc_masked_per_h.append(float('nan'))

    test_ret_masked_weights = horizon_weights_np[test_ret_masked_valid]
    test_vol_masked_weights = horizon_weights_np[test_vol_masked_valid]
    avg_test_ret_loss_masked = float(
        np.dot(test_ret_loss_masked_per_h[test_ret_masked_valid], test_ret_masked_weights)
        / max(test_ret_masked_weights.sum(), 1e-12)
    ) if test_ret_masked_weights.size else float('nan')
    avg_test_vol_loss_masked = float(
        np.dot(test_vol_loss_masked_per_h[test_vol_masked_valid], test_vol_masked_weights)
        / max(test_vol_masked_weights.sum(), 1e-12)
    ) if test_vol_masked_weights.size else float('nan')

    print(
        f"[test] ret={format_metric(avg_test_ret_loss_per_h, '{:.4e}')} (w_avg={float(np.dot(avg_test_ret_loss_per_h, horizon_weights_np) / max(horizon_weights_cpu.sum().item(), 1e-12)):.4e})  "
        f"vol={format_metric(avg_test_vol_loss_per_h, '{:.4e}')} (w_avg={float(np.dot(avg_test_vol_loss_per_h, horizon_weights_np) / max(horizon_weights_cpu.sum().item(), 1e-12)):.4e})  "
        f"ret(mask)={format_metric(test_ret_loss_masked_per_h, '{:.4e}')} (w_avg={avg_test_ret_loss_masked:.4e})  "
        f"vol(mask)={format_metric(test_vol_loss_masked_per_h, '{:.4e}')} (w_avg={avg_test_vol_loss_masked:.4e})  "
        f"BCE(all)={format_metric(test_dir_bce_per_h, '{:.4e}')}  Acc(all)={format_metric(test_accuracy_per_h, '{:.4f}')}  "
        f"AUC(all)={format_metric(test_auc_per_h, '{:.4f}')}"
    )
    print(
        f"  BCE(mask)={format_metric(test_dir_bce_masked_per_h, '{:.4e}')}  Acc(mask)={format_metric(test_acc_masked_per_h, '{:.4f}')}  "
        f"AUC(mask)={format_metric(test_auc_masked_per_h, '{:.4f}')}"
    )

    print("[done] Training complete.")

# ---------------- Lightweight HFTDataset (when loading into RAM) ----------------
class HFTDataset(Dataset):
    def __init__(self, X: np.ndarray, y: np.ndarray):
        self.X = X.astype(np.float32, copy=False)
        self.y = y.astype(np.float32, copy=False)
    def __len__(self): return int(self.y.shape[0])
    def __getitem__(self, idx): 
        return torch.from_numpy(self.X[idx]), torch.from_numpy(self.y[idx])

# ---------------- Entry ----------------
if __name__ == "__main__":
    train_from_offline()
