#!/usr/bin/env python3
"""
Rebuild order-book snapshots from Bybit OB delta streams.

This script reads OUT_ROOT/meta.json generated by offline_ingest and rebuilds
snapshots for weeks_in_order.

Snapshots are OB-only event-time snapshots.
Each row is emitted at repaired OB event timestamps.
There is no time-grid interpolation in this pipeline.
Contract matches decision_time_basis = "ob_event_time".

Outputs snapshots.npz files compatible with RL_exec.load_raw_snapshots.
The snapshots payload is always a 4-column top-of-book matrix:
  (best_bid, best_ask, best_bid_size, best_ask_size).
RL execution expects this exact schema.

Env defaults:
  BYBIT_OB_DIR=/home/gabrool/Documents/OB
  BYBIT_OUT_ROOT=/media/gabrool/Expansion/Gabriel/bybit_offline_dt
  BYBIT_WEEKS=""  # optional comma-separated week keys
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np

from CMSSL17 import (
    FeatureEngine,
    _open_text,
)


# fast json if available
_orjson_spec = importlib.util.find_spec("orjson")
if _orjson_spec is not None:
    import orjson as _fastjson

    def fast_json_loads(s: str):
        return _fastjson.loads(s)
else:
    def fast_json_loads(s: str):
        return json.loads(s)


OB_DIR = os.environ.get("BYBIT_OB_DIR", "/home/gabrool/Documents/OB")
OUT_ROOT = os.environ.get("BYBIT_OUT_ROOT", "/media/gabrool/Expansion/Gabriel/bybit_offline_dt")
RAW_BYBIT_WEEKS = os.environ.get("BYBIT_WEEKS", "")
OB_DAILY_RE = re.compile(r"^(?P<d>\d{4}-\d{2}-\d{2})_BTCUSDT_.*ob.*\.zip$", re.IGNORECASE)


def _env_bool_int(name: str, default: int = 0) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return int(default)
    v = str(raw).strip().lower()
    if v in {"1", "true", "t", "yes", "y", "on"}:
        return 1
    if v in {"0", "false", "f", "no", "n", "off"}:
        return 0
    return int(v)


# Quality/repair env config (parsed once at import time)
BYBIT_DAY_CLIP = int(os.environ.get("BYBIT_DAY_CLIP", "1"))
BYBIT_TS_BACKSTEP_CLAMP_MS = int(os.environ.get("BYBIT_TS_BACKSTEP_CLAMP_MS", "5000"))
BYBIT_STRICT_DATA = _env_bool_int("BYBIT_STRICT_DATA", 0)
BYBIT_BAD_EXAMPLES_N = int(os.environ.get("BYBIT_BAD_EXAMPLES_N", "25"))
BYBIT_BAD_FRAC_ABORT = float(os.environ.get("BYBIT_BAD_FRAC_ABORT", "0.005"))
BYBIT_BAD_ABS_ABORT = int(os.environ.get("BYBIT_BAD_ABS_ABORT", "50000"))
ONE_DAY = timedelta(days=1)


def quality_env_config() -> dict[str, object]:
    """Serializable quality/repair env knobs for reports/metadata."""
    return {
        "day_clip": int(BYBIT_DAY_CLIP),
        "ts_backstep_clamp_ms": int(BYBIT_TS_BACKSTEP_CLAMP_MS),
        "strict_data": int(BYBIT_STRICT_DATA),
        "bad_examples_n": int(BYBIT_BAD_EXAMPLES_N),
        "bad_frac_abort": float(BYBIT_BAD_FRAC_ABORT),
        "bad_abs_abort": int(BYBIT_BAD_ABS_ABORT),
    }


def _ob_ext_rank(path: str) -> int:
    lower_path = str(path).lower()
    if lower_path.endswith(".data.zip"):
        return 0
    p = Path(path)
    if p.suffix.lower() == ".zip":
        return 1
    return 2


def _choose_preferred_daily_ob_path(candidates: List[str]) -> str:
    def _sort_key(path: str) -> tuple[int, str, str]:
        p = Path(path)
        return (_ob_ext_rank(path), p.name, str(p))

    return min(candidates, key=_sort_key)


def _parse_requested_weeks(raw: str) -> List[str]:
    items = [wk.strip() for wk in re.split(r"[\s,]+", raw) if wk.strip()]
    return items


def _parse_ymd_date(s: str) -> date:
    return datetime.strptime(s, "%Y-%m-%d").date()


def extract_week_key_from_name(name: str) -> str:
    m = re.search(r"\d{2}-\d{2}-\d{4}-to-\d{2}-\d{2}-\d{4}", name)
    if m:
        return m.group(0)
    raise ValueError(f"Could not extract week key from file name: {name}")


def _parse_week_key(week_key: str) -> Tuple[datetime, datetime, str]:
    m = re.fullmatch(r"(\d{2}-\d{2}-\d{4})-to-(\d{2}-\d{2}-\d{4})", week_key)
    if not m:
        raise ValueError(f"Unrecognized week key: {week_key}")
    s = datetime.strptime(m.group(1), "%d-%m-%Y")
    e = datetime.strptime(m.group(2), "%d-%m-%Y")
    return s, e, week_key


def _build_ob_daily_map(ob_dir: str) -> dict[date, str]:
    by_day: dict[date, str] = {}
    for path in sorted(Path(ob_dir).iterdir()):
        if not path.is_file():
            continue
        m = OB_DAILY_RE.match(path.name)
        if not m:
            continue
        day = _parse_ymd_date(m.group("d"))
        current = by_day.get(day)
        candidate = str(path)
        if current is None:
            by_day[day] = candidate
            continue
        chosen = _choose_preferred_daily_ob_path([current, candidate])
        if chosen != current:
            by_day[day] = candidate
        print(
            f"[warn] duplicate daily OB for {day.isoformat()}: "
            f"{Path(current).name} vs {path.name}; using {Path(chosen).name}"
        )
    return by_day


def _utc_day_bounds_ms(day: date) -> tuple[int, int]:
    assert ONE_DAY.total_seconds() > 0, "ONE_DAY must be positive and non-zero"
    start = datetime(day.year, day.month, day.day, tzinfo=timezone.utc)
    end = start + timedelta(days=1)
    return int(start.timestamp() * 1000), int(end.timestamp() * 1000)


@dataclass
class SnapshotSeries:
    ts: List[int]
    best_bid: List[float]
    best_ask: List[float]
    best_bid_size: List[float]
    best_ask_size: List[float]
    time_since_last_ob_update_ms: List[float]

    def append(
        self,
        ts_ms: int,
        bid: float,
        ask: float,
        bid_size: float,
        ask_size: float,
        stale_ms: float,
    ) -> None:
        # Invariant: every per-row series must be appended in lockstep.
        self.ts.append(int(ts_ms))
        self.best_bid.append(float(bid))
        self.best_ask.append(float(ask))
        self.best_bid_size.append(float(bid_size))
        self.best_ask_size.append(float(ask_size))
        self.time_since_last_ob_update_ms.append(max(float(stale_ms), 0.0))

    def to_npz(self, path: Path) -> None:
        """Save snapshot arrays.

        Schema:
          - ts: int64 ms timestamps
          - snapshots: float32 [N,4] = (best_bid, best_ask, best_bid_size, best_ask_size)

        Example row:
          snapshots[i] = [63125.5, 63126.0, 4.2, 3.8]

        RL execution requires this 4-field format.
        """
        # Invariant: all per-row arrays must remain equal length.
        n_rows = len(self.ts)
        if not (
            n_rows
            == len(self.best_bid)
            == len(self.best_ask)
            == len(self.best_bid_size)
            == len(self.best_ask_size)
            == len(self.time_since_last_ob_update_ms)
        ):
            raise ValueError("SnapshotSeries arrays have mismatched lengths")
        snapshots = np.column_stack(
            [self.best_bid, self.best_ask, self.best_bid_size, self.best_ask_size]
        ).astype(np.float32)
        np.savez_compressed(
            path,
            ts=np.asarray(self.ts, dtype=np.int64),
            snapshots=snapshots,
            time_since_last_ob_update_ms=np.asarray(self.time_since_last_ob_update_ms, dtype=np.float32),
        )


@dataclass
class DayQuality:
    day: str
    ob_path: str
    counters: dict[str, dict[str, int]]
    raw_ts_min: Optional[int] = None
    raw_ts_max: Optional[int] = None
    out_ts_min: Optional[int] = None
    out_ts_max: Optional[int] = None
    examples: Optional[dict[str, list[dict[str, object]]]] = None
    abort_flags: Optional[dict[str, bool]] = None

    def __post_init__(self) -> None:
        if self.examples is None:
            self.examples = {}
        if self.abort_flags is None:
            self.abort_flags = {}

    def increment_counter(self, namespace: str, key: str, amount: int = 1) -> None:
        ns = self.counters.setdefault(namespace, {})
        ns[key] = int(ns.get(key, 0) + amount)

    def update_raw_ts(self, ts_ms: int) -> None:
        ts = int(ts_ms)
        self.raw_ts_min = ts if self.raw_ts_min is None else min(self.raw_ts_min, ts)
        self.raw_ts_max = ts if self.raw_ts_max is None else max(self.raw_ts_max, ts)

    def update_output_ts(self, ts_ms: int) -> None:
        ts = int(ts_ms)
        self.out_ts_min = ts if self.out_ts_min is None else min(self.out_ts_min, ts)
        self.out_ts_max = ts if self.out_ts_max is None else max(self.out_ts_max, ts)

    def append_example(self, category: str, payload: dict[str, object]) -> None:
        assert self.examples is not None
        bucket = self.examples.setdefault(category, [])
        if len(bucket) < BYBIT_BAD_EXAMPLES_N:
            bucket.append(dict(payload))

    def set_abort_flag(self, flag: str, value: bool = True) -> None:
        assert self.abort_flags is not None
        self.abort_flags[flag] = bool(value)

    def to_dict(self) -> dict[str, object]:
        return {
            "day": self.day,
            "ob_path": self.ob_path,
            "counters": {ns: dict(vals) for ns, vals in self.counters.items()},
            "raw_ts": {"min": self.raw_ts_min, "max": self.raw_ts_max},
            "output_ts": {"min": self.out_ts_min, "max": self.out_ts_max},
            "examples": {k: list(v) for k, v in (self.examples or {}).items()},
            "abort_flags": dict(self.abort_flags or {}),
        }


@dataclass
class WeekQuality:
    week_key: str
    days: list[DayQuality]
    totals: dict[str, dict[str, int]]
    tainted: bool = False
    notes: Optional[list[str]] = None

    def __post_init__(self) -> None:
        if self.notes is None:
            self.notes = []

    def add_day(self, day_quality: DayQuality) -> None:
        self.days.append(day_quality)

    def increment_total(self, namespace: str, key: str, amount: int = 1) -> None:
        ns = self.totals.setdefault(namespace, {})
        ns[key] = int(ns.get(key, 0) + amount)

    def append_note(self, note: str) -> None:
        assert self.notes is not None
        self.notes.append(str(note))

    def recompute_totals(self) -> None:
        self.totals = {
            "parse": {},
            "event": {},
            "backstep": {},
            "day_clip": {},
        }
        for day in self.days:
            for namespace, values in day.counters.items():
                ns = self.totals.setdefault(namespace, {})
                for key, value in values.items():
                    ns[key] = int(ns.get(key, 0) + int(value))
            if any((day.abort_flags or {}).values()):
                self.tainted = True

    def to_dict(self) -> dict[str, object]:
        return {
            "week_key": self.week_key,
            "days": [d.to_dict() for d in self.days],
            "totals": {ns: dict(vals) for ns, vals in self.totals.items()},
            "tainted": bool(self.tainted),
            "notes": list(self.notes or []),
        }


def _day_bad_abs_and_total(day_quality: DayQuality) -> tuple[int, int]:
    """Compute corruption and total counts for snapshot day quality."""
    bad_abs = 0
    for namespace in ("parse", "event", "backstep", "day_clip"):
        for key, value in day_quality.counters.get(namespace, {}).items():
            key_l = str(key).lower()
            if "drop" in key_l or "error" in key_l or "bad" in key_l:
                bad_abs += int(value)
    total = int(day_quality.counters.get("event", {}).get("total", 0))
    return int(bad_abs), int(total)


def build_snapshots_from_ob_files(ob_paths: List[str], week_quality: WeekQuality) -> SnapshotSeries:
    fe = FeatureEngine()
    series = SnapshotSeries(
        ts=[],
        best_bid=[],
        best_ask=[],
        best_bid_size=[],
        best_ask_size=[],
        time_since_last_ob_update_ms=[],
    )

    last_seen_ts_ms: Optional[int] = None

    for ob_path in ob_paths:
        day_match = OB_DAILY_RE.match(Path(ob_path).name)
        if day_match is None:
            raise ValueError(f"Could not parse day from OB file name: {ob_path}")
        day = _parse_ymd_date(day_match.group("d"))
        day_start_ms, day_end_ms = _utc_day_bounds_ms(day)

        dq_day = DayQuality(day=day.isoformat(), ob_path=ob_path, counters={})
        aborted_for_corruption = False

        with _open_text(ob_path) as f:
            for line_no, line in enumerate(f, start=1):
                dq_day.increment_counter("event", "total")
                if not line:
                    continue
                try:
                    raw = fast_json_loads(line)
                except Exception:
                    dq_day.increment_counter("parse", "bad_json")
                    dq_day.append_example(
                        "bad_json",
                        {"line": int(line_no), "sample": line[:200].rstrip()},
                    )
                    raw = None

                if raw is not None:
                    try:
                        etype, ts_ms_raw, payload = fe._parse_event(raw)
                    except Exception:
                        dq_day.increment_counter("parse", "parse_fail")
                        dq_day.append_example("parse_fail", {"line": int(line_no)})
                        raw = None

                if raw is None:
                    bad_abs, total = _day_bad_abs_and_total(dq_day)
                    bad_frac = float(bad_abs) / float(max(1, total))
                    if bad_abs >= BYBIT_BAD_ABS_ABORT or bad_frac >= BYBIT_BAD_FRAC_ABORT:
                        aborted_for_corruption = True
                        dq_day.set_abort_flag("aborted_due_to_corruption", True)
                        week_quality.tainted = True
                        week_quality.append_note(
                            "[warn] corruption abort day="
                            f"{dq_day.day} file={Path(ob_path).name} bad_abs={bad_abs} total={total} "
                            f"bad_frac={bad_frac:.6f} thresholds(abs={BYBIT_BAD_ABS_ABORT}, frac={BYBIT_BAD_FRAC_ABORT})"
                        )
                        break
                    continue

                if etype != "ob":
                    dq_day.increment_counter("event", "non_ob")
                    bad_abs, total = _day_bad_abs_and_total(dq_day)
                    bad_frac = float(bad_abs) / float(max(1, total))
                    if bad_abs >= BYBIT_BAD_ABS_ABORT or bad_frac >= BYBIT_BAD_FRAC_ABORT:
                        aborted_for_corruption = True
                        dq_day.set_abort_flag("aborted_due_to_corruption", True)
                        week_quality.tainted = True
                        week_quality.append_note(
                            "[warn] corruption abort day="
                            f"{dq_day.day} file={Path(ob_path).name} bad_abs={bad_abs} total={total} "
                            f"bad_frac={bad_frac:.6f} thresholds(abs={BYBIT_BAD_ABS_ABORT}, frac={BYBIT_BAD_FRAC_ABORT})"
                        )
                        break
                    continue

                ts_ms_raw = int(ts_ms_raw)
                dq_day.update_raw_ts(ts_ms_raw)
                if BYBIT_DAY_CLIP and (ts_ms_raw < day_start_ms or ts_ms_raw >= day_end_ms):
                    dq_day.increment_counter("day_clip", "clipped")
                    dq_day.append_example("day_clip", {"line": int(line_no), "ts_raw": int(ts_ms_raw)})
                    bad_abs, total = _day_bad_abs_and_total(dq_day)
                    bad_frac = float(bad_abs) / float(max(1, total))
                    if bad_abs >= BYBIT_BAD_ABS_ABORT or bad_frac >= BYBIT_BAD_FRAC_ABORT:
                        aborted_for_corruption = True
                        dq_day.set_abort_flag("aborted_due_to_corruption", True)
                        week_quality.tainted = True
                        week_quality.append_note(
                            "[warn] corruption abort day="
                            f"{dq_day.day} file={Path(ob_path).name} bad_abs={bad_abs} total={total} "
                            f"bad_frac={bad_frac:.6f} thresholds(abs={BYBIT_BAD_ABS_ABORT}, frac={BYBIT_BAD_FRAC_ABORT})"
                        )
                        break
                    continue

                repaired_ts_ms = ts_ms_raw
                if last_seen_ts_ms is not None and repaired_ts_ms < last_seen_ts_ms:
                    backstep_ms = last_seen_ts_ms - repaired_ts_ms
                    if BYBIT_STRICT_DATA:
                        raise ValueError(
                            "Non-decreasing repaired OB event timestamps violated: "
                            f"previous_ts_ms={last_seen_ts_ms} current_ts_ms={repaired_ts_ms} "
                            f"raw_ts_ms={ts_ms_raw}. strict_data=1"
                        )
                    if backstep_ms <= BYBIT_TS_BACKSTEP_CLAMP_MS:
                        repaired_ts_ms = last_seen_ts_ms
                        dq_day.increment_counter("backstep", "clamp")
                    else:
                        dq_day.increment_counter("backstep", "drop")
                        dq_day.append_example(
                            "backstep_drop",
                            {"line": int(line_no), "prev_ts": int(last_seen_ts_ms), "curr_ts": int(ts_ms_raw)},
                        )
                        bad_abs, total = _day_bad_abs_and_total(dq_day)
                        bad_frac = float(bad_abs) / float(max(1, total))
                        if bad_abs >= BYBIT_BAD_ABS_ABORT or bad_frac >= BYBIT_BAD_FRAC_ABORT:
                            aborted_for_corruption = True
                            dq_day.set_abort_flag("aborted_due_to_corruption", True)
                            week_quality.tainted = True
                            week_quality.append_note(
                                "[warn] corruption abort day="
                                f"{dq_day.day} file={Path(ob_path).name} bad_abs={bad_abs} total={total} "
                                f"bad_frac={bad_frac:.6f} thresholds(abs={BYBIT_BAD_ABS_ABORT}, frac={BYBIT_BAD_FRAC_ABORT})"
                            )
                            break
                        continue
                last_seen_ts_ms = repaired_ts_ms
                dq_day.update_output_ts(repaired_ts_ms)

                if isinstance(payload, tuple):
                    tp_code, bids, asks = int(payload[0]), payload[1], payload[2]
                else:
                    data = payload.get("data", payload)
                    tp_code = 1 if str(payload.get("type") or data.get("type") or payload.get("DataType") or "delta").strip().lower() == "snapshot" else 2
                    bids = tuple((float(p), float(q)) for p, q in data.get("b", []))
                    asks = tuple((float(p), float(q)) for p, q in data.get("a", []))

                fe._update_book_from_ob(tp_code, bids, asks)
                bid, ask, bsz, asz = fe._book_best()
                if bid <= 0.0 or ask <= 0.0 or bsz is None or asz is None:
                    continue
                bsz = max(float(bsz), 0.0)
                asz = max(float(asz), 0.0)

                if series.ts and series.ts[-1] == repaired_ts_ms:
                    series.best_bid[-1] = float(bid)
                    series.best_ask[-1] = float(ask)
                    series.best_bid_size[-1] = float(bsz)
                    series.best_ask_size[-1] = float(asz)
                    series.time_since_last_ob_update_ms[-1] = 0.0
                    continue

                series.append(repaired_ts_ms, bid, ask, bsz, asz, 0.0)

                bad_abs, total = _day_bad_abs_and_total(dq_day)
                bad_frac = float(bad_abs) / float(max(1, total))
                if bad_abs >= BYBIT_BAD_ABS_ABORT or bad_frac >= BYBIT_BAD_FRAC_ABORT:
                    aborted_for_corruption = True
                    dq_day.set_abort_flag("aborted_due_to_corruption", True)
                    week_quality.tainted = True
                    week_quality.append_note(
                        "[warn] corruption abort day="
                        f"{dq_day.day} file={Path(ob_path).name} bad_abs={bad_abs} total={total} "
                        f"bad_frac={bad_frac:.6f} thresholds(abs={BYBIT_BAD_ABS_ABORT}, frac={BYBIT_BAD_FRAC_ABORT})"
                    )
                    break

        bad_abs, total = _day_bad_abs_and_total(dq_day)
        dq_day.increment_counter("event", "bad_abs", bad_abs)
        dq_day.increment_counter("event", "bad_total", total)
        week_quality.add_day(dq_day)

        parse_bad_json = dq_day.counters.get("parse", {}).get("bad_json", 0)
        parse_fail = dq_day.counters.get("parse", {}).get("parse_fail", 0)
        non_ob = dq_day.counters.get("event", {}).get("non_ob", 0)
        day_clipped = dq_day.counters.get("day_clip", {}).get("clipped", 0)
        backstep_drop = dq_day.counters.get("backstep", {}).get("drop", 0)
        backstep_clamp = dq_day.counters.get("backstep", {}).get("clamp", 0)
        if parse_bad_json or parse_fail or non_ob or day_clipped or backstep_drop or backstep_clamp or aborted_for_corruption:
            print(
                f"[quality] {Path(ob_path).name}: "
                f"bad_json={parse_bad_json:,} parse_fail={parse_fail:,} non_ob={non_ob:,} day_clipped={day_clipped:,} "
                f"backstep_clamp={backstep_clamp:,} backstep_drop={backstep_drop:,} "
                f"aborted={int(aborted_for_corruption)}"
            )

    week_quality.recompute_totals()
    return series


def load_weeks_in_order(out_root: str) -> List[str]:
    meta_path = Path(out_root) / "meta.json"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"Missing {meta_path}. Run offline_ingest first to create OUT_ROOT/meta.json."
        )
    with meta_path.open("r", encoding="utf-8") as f:
        meta = json.load(f)
    weeks = meta.get("weeks_in_order")
    if not isinstance(weeks, list) or not all(isinstance(x, str) for x in weeks):
        raise ValueError("meta.json missing valid weeks_in_order list[str].")
    return weeks


def validate_metadata_contract(out_root: str) -> None:
    """Validate offline_ingest metadata contract required by offline snapshots."""
    meta_path = Path(out_root) / "meta.json"
    if not meta_path.exists():
        raise FileNotFoundError(
            f"Missing {meta_path}. Run offline_ingest first to create OUT_ROOT/meta.json."
        )
    with meta_path.open("r", encoding="utf-8") as f:
        meta = json.load(f)

    decision_time_basis = meta.get("decision_time_basis")
    if decision_time_basis != "ob_event_time":
        raise ValueError(
            "Unsupported metadata contract in OUT_ROOT/meta.json: "
            f"decision_time_basis={decision_time_basis!r}. "
            "Required decision_time_basis='ob_event_time'."
        )

    decision_policy = meta.get("decision_policy")
    if decision_policy is not None and decision_policy != "ob_event_time":
        if decision_policy == "ob_only_grid_quantized":
            raise ValueError(
                "Rejected deprecated grid decision policy in OUT_ROOT/meta.json: "
                "decision_policy='ob_only_grid_quantized'. "
                "This snapshot builder only supports ob_event_time policy metadata."
            )
        raise ValueError(
            "Unsupported metadata contract in OUT_ROOT/meta.json: "
            f"decision_policy={decision_policy!r}. "
            "Required decision_policy='ob_event_time' when decision_policy is present."
        )


def filter_weeks(weeks_in_order: List[str], requested: Optional[List[str]]) -> List[str]:
    if not requested:
        return weeks_in_order
    req = {extract_week_key_from_name(x) for x in requested}
    return [wk for wk in weeks_in_order if wk in req]


def daily_ob_paths_for_week(week_key: str, ob_by_day: dict[date, str]) -> List[str]:
    assert ONE_DAY.total_seconds() > 0, "ONE_DAY must be positive and non-zero"
    start_dt, end_dt, _ = _parse_week_key(week_key)
    d0, d1 = start_dt.date(), end_dt.date()
    paths = []
    missing = []
    d = d0
    while d <= d1:
        p = ob_by_day.get(d)
        if p is None:
            missing.append(d.strftime("%Y-%m-%d"))
        else:
            paths.append(p)
        d += ONE_DAY
    if missing:
        raise ValueError(f"Missing daily OB files for week={week_key}: {missing}")
    return paths


def write_week_snapshots(out_root: str, week_key: str, series: SnapshotSeries, *, overwrite: bool) -> Path:
    week_dir = Path(out_root) / week_key
    week_dir.mkdir(parents=True, exist_ok=True)
    out_path = week_dir / "snapshots.npz"
    if out_path.exists() and not overwrite:
        raise FileExistsError(f"Snapshot file exists: {out_path} (use --overwrite)")
    series.to_npz(out_path)
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ob-dir",
        default=OB_DIR,
        help="Directory containing daily OB zips like YYYY-MM-DD_BTCUSDT_ob200.data.zip",
    )
    parser.add_argument("--out-root", default=OUT_ROOT, help="Output root matching offline_ingest")
    parser.add_argument("--weeks", default=RAW_BYBIT_WEEKS, help="Comma-separated week keys")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing snapshot files")
    args = parser.parse_args()

    validate_metadata_contract(args.out_root)
    weeks_in_order = load_weeks_in_order(args.out_root)
    requested = _parse_requested_weeks(args.weeks) if args.weeks else None
    weeks = filter_weeks(weeks_in_order, requested)
    if not weeks:
        raise ValueError(
            f"No matching weeks found for requested filter. "
            f"requested={requested or []} available={weeks_in_order}"
        )

    ob_by_day = _build_ob_daily_map(args.ob_dir)
    if not ob_by_day:
        raise FileNotFoundError(
            f"No daily OB files found in {args.ob_dir}. "
            "Expected files like YYYY-MM-DD_BTCUSDT_ob200.data.zip"
        )

    for wk in weeks:
        ob_paths = daily_ob_paths_for_week(wk, ob_by_day)
        print(
            f"[snapshots] week={wk} "
            f"ob={os.path.basename(ob_paths[0])}...{os.path.basename(ob_paths[-1])} "
            f"({len(ob_paths)} files)"
        )
        week_quality = WeekQuality(week_key=wk, days=[], totals={})
        series = build_snapshots_from_ob_files(ob_paths, week_quality)
        quality_path = Path(args.out_root) / wk / "snapshots_quality.json"
        quality_payload = {
            "config": quality_env_config(),
            **week_quality.to_dict(),
        }
        quality_path.parent.mkdir(parents=True, exist_ok=True)
        quality_path.write_text(json.dumps(quality_payload, indent=2), encoding="utf-8")
        if not series.ts:
            print(f"  [skip] no snapshots produced for {wk}")
            print(f"  [quality] {quality_path}")
            continue
        out_path = write_week_snapshots(args.out_root, wk, series, overwrite=args.overwrite)
        print(f"  [write] {out_path} rows={len(series.ts):,}")
        print(f"  [quality] {quality_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
