"""Shared colocated-balanced execution CLI defaults."""

from __future__ import annotations

from mmrt.execution.contracts import QueueModelMode

DEFAULT_CANCEL_GUARD_TICKS = 1

DEFAULT_MAX_DISTANCE_TICKS = 2
DEFAULT_DEFAULT_ORDER_QTY = 0.001
DEFAULT_MAX_ORDER_QTY = 0.003
DEFAULT_POST_ONLY_GAP_TICKS = 1

DEFAULT_QUEUE_MODE = QueueModelMode.BALANCED
DEFAULT_L2_DECREASE_WEIGHT = 0.5
DEFAULT_TRADE_AT_LEVEL_WEIGHT = 1.0
DEFAULT_UNKNOWN_LEVEL_QUEUE_AHEAD_QTY = 0.0
DEFAULT_DEDUPE_L2_DECREASE_WITH_TRADE_PRINTS = True

DEFAULT_DECISION_COMPUTE_LATENCY_US = 50
DEFAULT_ORDER_ENTRY_LATENCY_US = 250
DEFAULT_CANCEL_LATENCY_US = 250

DEFAULT_MAKER_FEE_BPS = -0.5

DEFAULT_ORDER_QTY = 0.001
DEFAULT_FILL_HORIZON_US = 1_000_000
DEFAULT_ADVERSE_HORIZON_US = 1_000_000
DEFAULT_QTY_EPSILON = 1e-12
